[package]
name = "jaiba-runtime"
description = "Runtime concurrente y persistente para grafos Jaiba"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
oracle-driver = ["dep:oracle"]
sqlserver-driver = ["dep:tiberius", "dep:tokio-util"]
kafka-driver = ["dep:rdkafka"]
mongodb-driver = ["dep:mongodb"]

[dependencies]
jaiba-core = { path = "../jaiba-core" }
jaiba-connection-manager = { path = "../jaiba-connection-manager" }
jaiba-plugin-sdk = { path = "../jaiba-plugin-sdk" }
async-trait.workspace = true
csv.workspace = true
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
sha2.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
uuid.workspace = true
oracle = { workspace = true, optional = true }
tiberius = { workspace = true, optional = true }
tokio-util = { workspace = true, optional = true }
rdkafka = { workspace = true, optional = true }
mongodb = { workspace = true, optional = true }
reqwest.workspace = true
